version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - server
      - rag
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - rag
  rag:
    build: ./rag
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
